name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build.yml

  package:
    name: Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-output-*
          path: final-bundle
          merge-multiple: true

      - name: Bundle Bin Into Zip
        run: cd final-bundle && zip -r ../LuauGDExtension-bin.zip .

      - name: Upload Zipped Bundle
        uses: actions/upload-artifact@v4
        with:
          name: LuauGDExtension-bin-zip
          path: LuauGDExtension-bin.zip

      - name: Upload Combined Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luau GDExtension
          path: final-bundle/
